.TH "src/backend/Pkg.cpp" 3 "Fri Dec 14 2018" "Version 1.0.0" "Pkg-Mgr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/backend/Pkg.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Pkg\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Thomas Lenz thomas.lenz96@gmail.com AS The2b 
.RE
.PP
\fBDate:\fP
.RS 4
08 November 2018  Package Manager
.RE
.PP
-100 
.SH "Author"
.PP 
Generated automatically by Doxygen for Pkg-Mgr from the source code\&.
